# Generated by Django 4.1.3 on 2023-09-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdmycomicsapi', '0002_remove_book_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
