# Generated by Django 4.1.3 on 2023-09-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdmycomicsapi', '0003_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
