# Generated by Django 4.2.3 on 2023-09-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdmycomicsapi', '0004_book_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
